version: 2
registries:
  github-teamwork:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.GH_ADMIN_TOKEN}}
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"