version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"