name: Release

on:
  push:
    branches:
      - staging
    tags:
      - 'v*.*.*'
  workflow_dispatch:
env:
  GO_VERSION: "1.24.x"

jobs:
  release-image:
    runs-on: [self-hosted, staging, default]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.AWS_ECR_MASTER_ACCOUNT }}.dkr.ecr.${{ vars.AWS_ECR_MASTER_REGION }}.amazonaws.com
          username: ${{ secrets.AWS_ECR_MASTER_ACCESS_KEY }}
          password: ${{ secrets.AWS_ECR_MASTER_SECRET_ACCESS_KEY }}

      - run: docker context create builders
      - uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders
          driver-opts: |
            image=${{ vars.AWS_ECR_MASTER_ACCOUNT }}.dkr.ecr.${{ vars.AWS_ECR_MASTER_REGION }}.amazonaws.com/proxy/moby/buildkit:buildx-stable-1

      - name: Checkout Teamwork Central Build Actions
        uses: actions/checkout@v4
        with:
          repository: Teamwork/gha-builds
          ref: main
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          path: .github/actions/build
          persist-credentials: false

      - name: Go Build
        uses: ./.github/actions/build/go/default
        with:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          ECR_ACCOUNT: ${{ vars.AWS_ECR_MASTER_ACCOUNT }}
          ECR_REGION: ${{ vars.AWS_ECR_MASTER_REGION }}
          ECR_ACCESS_KEY: ${{ secrets.AWS_ECR_MASTER_ACCESS_KEY }}
          ECR_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECR_MASTER_SECRET_ACCESS_KEY }}
          IMAGE_REPO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_REPO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME: "mcp"
          HELM_CHART_PATH: "chart"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PUSH_PROD: true
          PUSH_DEV_ENV: false
          UPDATE_HELM_CHART: true
          NPM_TOKEN: false

  release-binaries:
    runs-on: [self-hosted, staging, default]
    needs: release-image
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Version
        id: version
        run: |
          version="${GITHUB_REF#refs/tags/}"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Go Build
        run: |
          version="${{ steps.version.outputs.version }}"

          mkdir -p releases
          GOOS=linux GOARCH=amd64 go build -ldflags="-X 'github.com/teamwork/mcp/internal/config.Version=$version'" -o releases/tw-mcp-linux-amd64 ./cmd/mcp-stdio
          GOOS=linux GOARCH=arm64 go build -ldflags="-X 'github.com/teamwork/mcp/internal/config.Version=$version'" -o releases/tw-mcp-linux-arm64 ./cmd/mcp-stdio
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X 'github.com/teamwork/mcp/internal/config.Version=$version'" -o releases/tw-mcp-darwin-amd64 ./cmd/mcp-stdio
          GOOS=darwin GOARCH=arm64 go build -ldflags="-X 'github.com/teamwork/mcp/internal/config.Version=$version'" -o releases/tw-mcp-darwin-arm64 ./cmd/mcp-stdio
          GOOS=windows GOARCH=amd64 go build -ldflags="-X 'github.com/teamwork/mcp/internal/config.Version=$version'" -o releases/tw-mcp-windows-amd64.exe ./cmd/mcp-stdio

      - name: Create Release
        run: |
          version="${{ steps.version.outputs.version }}"
          gh release create $version \
            --fail-on-no-commits \
            --generate-notes \
            --verify-tag \
            releases/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}