name: Staging sync
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync staging branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/staging; then
            git checkout staging
            git reset --hard origin/main
          else
            git checkout -b staging origin/main
          fi
          git push -f origin staging