name: Test
on:
  pull_request:
  push:
    branches:
      - main

env:
  GO_VERSION: "1.24.x"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Compile
        run: |
          go build ./cmd/mcp-http
          go build ./cmd/mcp-http-cli
          go build ./cmd/mcp-stdio

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download modules
        run: go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download modules
        run: go mod download

      - name: Test
        run: go test -v  ./...